version: '3.8'
volumes:
  mysql_vol: {}
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: meli_sprint_user
      MYSQL_PASSWORD: Meli_Sprint#123
      MYSQL_DATABASE: melisprint
    volumes:
      - mysql_vol:/var/lib/mysql